
name: debug
root: /data/seunan/CUDA_PixelMix
train: True
seed: 42
wandb: False

tm: True
num_target: 2
eval_target: 2



data:

  num_classes: 18

  source:
    dataset: 'gta5'
    kwargs:
      root: /local_datasets/GTA5
      list_path: ${root}/datasets/gta5_list
      base_size: [1024, 512]
      crop_size: [1024, 512]
      random_mirror: True
      random_crop: False
      resize: True
      gaussian_blur: True
      class_16: False
      
  target:
    dataset: 'IDD' # cityscapes or IDD or MapillaryVistas
    kwargs:
      root: /local_datasets/IDD/IDD
      list_path: ${root}/datasets/idd_list
      base_size: [1024, 512]
      crop_size: [1024, 512]
      random_mirror: True
      random_crop: False
      resize: True
      gaussian_blur: True
      class_16: False
      class_13: False



  loader:
    kwargs:
      batch_size: 1
      num_workers: 4
      pin_memory: True

  source_val_iterations: 100

model:
  backbone: deeplabv2_multi
  imagenet_pretrained: ${root}/pretrained/DeepLab_resnet_pretrained_init-f81d91e8.pth
  checkpoint: ${root}/best_path/t1.pth
  resume_from_checkpoint: True

opt:
  kind: "SGD"
  momentum: 0.9
  weight_decay: 5e-4
  lr: 1e-4
  iterations: 40000
  poly_power: 0.9

# For auxiliary mode output
aux: True
lam_aux: 0.1
lam_new: 0.1

# Exponential weighted average of model parameters
ema_decay: 0.999

# Perturbations
pseudolabel_threshold: 0.0
lam_aug: 0.1
lam_fourier: 0.0
lam_cutmix: 0.0

# Fourier
source_fourier: False
fourier_beta: 0.01

pseudobest_threshold: 0.0